exclude: ['README.md']
theme: jekyll-theme-cayman

# Setup
title:        Inmail.be
tagline:      Mail made simple!
baseurl:      ""

# About/contact
author:
  name:       Tom Rutsaert
  url:        http://inmail.be 