exclude: ['README.md']
theme: jekyll-theme-cayman

# Setup
title:        Inmail.be
tagline:      Mail made simple!
baseurl:      ""
paginate: 1

# About/contact
author:
  name:       Tom Rutsaert
  url:        http://inmail.be

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown